# Generated by Django 2.1.7 on 2019-07-21 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20190326_0201'),
        ('contest', '0010_contest_similarity_check_result'),
    ]

    operations = [
    ]
