# Generated by Django 2.1.7 on 2019-07-21 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_problem_share_submission'),
        ('problem', '0013_auto_20181227_0719'),
    ]

    operations = [
    ]
