# Generated by Django 2.1.7 on 2019-07-21 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_merge_20190721_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ('_id',)},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='pe_ignored',
        ),
    ]
